name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'cloud/aws/sns/sns-public-subscribe-access.yaml'
    - 'cloud/kubernetes/deployments/k8s-cpu-limits-not-set.yaml'
    - 'cloud/kubernetes/deployments/k8s-cpu-requests-not-set.yaml'
    - 'cloud/kubernetes/deployments/k8s-default-namespace-used.yaml'
    - 'cloud/kubernetes/deployments/k8s-host-ports-check.yaml'
    - 'cloud/kubernetes/deployments/k8s-image-pull-policy-always.yaml'
    - 'cloud/kubernetes/deployments/k8s-image-tag-not-fixed.yaml'
    - 'cloud/kubernetes/deployments/k8s-liveness-probe-not-configured.yaml'
    - 'cloud/kubernetes/deployments/k8s-memory-limits-not-set.yaml'
    - 'cloud/kubernetes/deployments/k8s-memory-requests-not-set.yaml'
    - 'cloud/kubernetes/deployments/k8s-minimize-added-capabilities.yaml'
    - 'cloud/kubernetes/deployments/k8s-privileged-container.yaml'
    - 'cloud/kubernetes/deployments/k8s-readiness-probe-not-set.yaml'
    - 'cloud/kubernetes/deployments/k8s-root-container-admission.yaml'
    - 'cloud/kubernetes/deployments/k8s-seccomp-profile-set.yaml'
    - 'cloud/kubernetes/kubernetes-code-env.yaml'
    - 'cloud/kubernetes/network-policies/k8s-netpol-egress-rules.yaml'
    - 'cloud/kubernetes/network-policies/k8s-netpol-namespace.yaml'
    - 'cloud/kubernetes/network-policies/k8s-network-ingress-rules.yaml'
    - 'cloud/kubernetes/pods/k8s-allow-privilege-escalation-set.yaml'
    - 'cloud/kubernetes/pods/k8s-containers-share-host-ipc.yaml'
    - 'cloud/kubernetes/pods/k8s-host-network-namespace-shared.yaml'
    - 'cloud/kubernetes/pods/k8s-host-pid-namespace-sharing.yaml'
    - 'cloud/kubernetes/pods/k8s-readonly-fs.yaml'
    - 'cloud/kubernetes/pods/k8s-readonly-rootfs.yaml'
    - 'cloud/kubernetes/pods/k8s-root-user-id.yaml'
    - 'cloud/kubernetes/security-compliance/k8s-audit-log-path-set.yaml'
    - 'cloud/kubernetes/security-compliance/k8s-enc-prov-conf.yaml'
    - 'cloud/kubernetes/security-compliance/k8s-etcd-cafile-set.yaml'
    - 'cloud/kubernetes/security-compliance/k8s-etcd-files-set.yaml'
    - 'cloud/kubernetes/security-compliance/k8s-ns-usage-check.yaml'
    - 'cloud/kubernetes/security-compliance/k8s-svc-acct-issuer-set.yaml'
    - 'cloud/kubernetes/security-compliance/k8s-svc-acct-key.yaml'
    - 'cloud/kubernetes/security-compliance/k8s-svc-acct-lookup-set.yaml'
    - 'cloud/kubernetes/security-compliance/k8s-tls-config-set.yaml'
    - 'dast/vulnerabilities/sqli/time-based-sqli.yaml'
    - 'file/malware/hash/anthem-deeppanda-malware-hash.yaml'
    - 'file/malware/hash/applejeus-malware-hash.yaml'
    - 'file/malware/hash/avburner-malware-hash.yaml'
    - 'file/malware/hash/backwash-malware-hash.yaml'
    - 'file/malware/hash/blackenergy-driver-amdide-hash.yaml'
    - 'file/malware/hash/blackenergy-driver-malware-hash.yaml'
    - 'file/malware/hash/blackenergy-killdisk-malware-hash.yaml'
    - 'file/malware/hash/blackenergy-ssh-malware-hash.yaml'
    - 'file/malware/hash/blackenergy-vbs-malware-hash.yaml'
    - 'file/malware/hash/bluelight-malware-hash.yaml'
    - 'file/malware/hash/bluetermite-emdivi-malware-hash.yaml'
    - 'file/malware/hash/bluetermite-emdivi-sfx-hash.yaml'
    - 'file/malware/hash/charmingcypress-malware-hash.yaml'
    - 'file/malware/hash/cheshirecat-malware-hash.yaml'
    - 'file/malware/hash/cloudduke-malware-hash.yaml'
    - 'file/malware/hash/codoso-gh0st-malware.yaml'
    - 'file/malware/hash/codoso-malware-hash.yaml'
    - 'file/malware/hash/codoso-pgv-malware-hash.yaml'
    - 'file/malware/hash/codoso-plugx-malware-hash.yaml'
    - 'file/malware/hash/disgomoji-malware-hash.yaml'
    - 'file/malware/hash/dubnium-malware-hash.yaml'
    - 'file/malware/hash/dubnium-sshopenssl-malware-hash.yaml'
    - 'file/malware/hash/emissary-malware-hash.yaml'
    - 'file/malware/hash/evilbamboo-malware-hash.yaml'
    - 'file/malware/hash/fakem-malware-hash.yaml'
    - 'file/malware/hash/flipflop-malware-hash.yaml'
    - 'file/malware/hash/furtim-malware-hash.yaml'
    - 'file/malware/hash/gimmick-malware-hash.yaml'
    - 'file/malware/hash/godzilla-webshell-hash.yaml'
    - 'file/malware/hash/greenbug-malware-hash.yaml'
    - 'file/malware/hash/ico-malware-hash.yaml'
    - 'file/malware/hash/industroyer-malware-hash.yaml'
    - 'file/malware/hash/ironPanda-htran-malware-hash.yaml'
    - 'file/malware/hash/ironpanda-dnstunclient-malware-hash.yaml'
    - 'file/malware/hash/ironpanda-malware-hash.yaml'
    - 'file/malware/hash/locky-ransomware-hash.yaml'
    - 'file/malware/hash/minidionis-readerview-malware-hash.yaml'
    - 'file/malware/hash/minidionis-vbs-malware-hash.yaml'
    - 'file/malware/hash/naikon-apt-malware-hash.yaml'
    - 'file/malware/hash/neuron2-malware-hash.yaml'
    - 'file/malware/hash/oilrig-malware-hash.yaml'
    - 'file/malware/hash/passcv-ntscan-malware-hash.yaml'
    - 'file/malware/hash/passcv-sabre-malware-hash.yaml'
    - 'file/malware/hash/passcv-signingcert-malware-hash.yaml'
    - 'file/malware/hash/petya-ransomware-hash.yaml'
    - 'file/malware/hash/poseidongroup-maldoc-malware-hash.yaml'
    - 'file/malware/hash/poseidongroup-malware-hash.yaml'
    - 'file/malware/hash/powerstar-malware-hash.yaml'
    - 'file/malware/hash/purplewave-malware-hash.yaml'
    - 'file/malware/hash/red-leaves-malware-hash.yaml'
    - 'file/malware/hash/regeorg-webshell-hash.yaml'
    - 'file/malware/hash/revil-ransomware-hash.yaml'
    - 'file/malware/hash/rokrat-malware-hash.yaml'
    - 'file/malware/hash/sauron-malware-hash.yaml'
    - 'file/malware/hash/seaduke-malware-hash.yaml'
    - 'file/malware/hash/sfx1-malware-hash.yaml'
    - 'file/malware/hash/sfxrar-acrotray-malware-hash.yaml'
    - 'file/malware/hash/sharpext-malware-hash.yaml'
    - 'file/malware/hash/sofacy-Winexe-malware-hash.yaml'
    - 'file/malware/hash/sofacy-bundestag-malware-hash.yaml'
    - 'file/malware/hash/sofacy-fybis-malware-hash.yaml'
    - 'file/malware/hash/tidepool-malware-hash.yaml'
    - 'file/malware/hash/turla-malware-hash.yaml'
    - 'file/malware/hash/unit78020-malware-hash.yaml'
    - 'file/malware/hash/upstyle-malware-hash.yaml'
    - 'file/malware/hash/wildneutron-malware-hash.yaml'
    - 'http/cves/2021/CVE-2021-38146.yaml'
    - 'http/cves/2021/CVE-2021-38147.yaml'
    - 'http/cves/2021/CVE-2021-43831.yaml'
    - 'http/cves/2021/CVE-2021-4436.yaml'
    - 'http/cves/2023/CVE-2023-32068.yaml'
    - 'http/cves/2023/CVE-2023-37645.yaml'
    - 'http/cves/2023/CVE-2023-38194.yaml'
    - 'http/cves/2023/CVE-2023-43472.yaml'
    - 'http/cves/2023/CVE-2023-45136.yaml'
    - 'http/cves/2023/CVE-2023-46732.yaml'
    - 'http/cves/2023/CVE-2023-48241.yaml'
    - 'http/cves/2023/CVE-2023-50719.yaml'
    - 'http/cves/2023/CVE-2023-50720.yaml'
    - 'http/cves/2023/CVE-2023-51449.yaml'
    - 'http/cves/2023/CVE-2023-6505.yaml'
    - 'http/cves/2023/CVE-2023-6786.yaml'
    - 'http/cves/2024/CVE-2024-0250.yaml'
    - 'http/cves/2024/CVE-2024-0939.yaml'
    - 'http/cves/2024/CVE-2024-1728.yaml'
    - 'http/cves/2024/CVE-2024-21650.yaml'
    - 'http/cves/2024/CVE-2024-23692.yaml'
    - 'http/cves/2024/CVE-2024-24112.yaml'
    - 'http/cves/2024/CVE-2024-24565.yaml'
    - 'http/cves/2024/CVE-2024-2621.yaml'
    - 'http/cves/2024/CVE-2024-27718.yaml'
    - 'http/cves/2024/CVE-2024-28995.yaml'
    - 'http/cves/2024/CVE-2024-29824.yaml'
    - 'http/cves/2024/CVE-2024-29895.yaml'
    - 'http/cves/2024/CVE-2024-29973.yaml'
    - 'http/cves/2024/CVE-2024-31750.yaml'
    - 'http/cves/2024/CVE-2024-31982.yaml'
    - 'http/cves/2024/CVE-2024-32113.yaml'
    - 'http/cves/2024/CVE-2024-3274.yaml'
    - 'http/cves/2024/CVE-2024-34982.yaml'
    - 'http/cves/2024/CVE-2024-3552.yaml'
    - 'http/cves/2024/CVE-2024-36412.yaml'
    - 'http/cves/2024/CVE-2024-36527.yaml'
    - 'http/cves/2024/CVE-2024-36837.yaml'
    - 'http/cves/2024/CVE-2024-37393.yaml'
    - 'http/cves/2024/CVE-2024-3922.yaml'
    - 'http/cves/2024/CVE-2024-4443.yaml'
    - 'http/default-logins/mantisbt/mantisbt-anonymous-login.yaml'
    - 'http/exposed-panels/lorex-panel.yaml'
    - 'http/exposed-panels/oracle-application-server-panel.yaml'
    - 'http/exposed-panels/trellix-panel.yaml'
    - 'http/exposed-panels/turnkey-lamp-panel.yaml'
    - 'http/exposed-panels/veeam-backup-manager-login.yaml'
    - 'http/exposed-panels/wildix-collaboration-panel.yaml'
    - 'http/misconfiguration/apache/apache-server-status-localhost.yaml'
    - 'http/misconfiguration/cookies-without-secure.yaml'
    - 'http/technologies/apache-allura-detect.yaml'
    - 'http/technologies/nperf-server-detect.yaml'
    - 'http/technologies/wordpress/plugins/copy-delete-posts.yaml'
    - 'http/technologies/wordpress/plugins/image-optimization.yaml'
    - 'http/technologies/wordpress/plugins/royal-elementor-addons.yaml'
    - 'http/technologies/wordpress/plugins/simple-history.yaml'
    - 'http/technologies/wordpress/plugins/sticky-header-effects-for-elementor.yaml'
    - 'http/technologies/wordpress/plugins/woocommerce-legacy-rest-api.yaml'
    - 'http/vulnerabilities/gradio/gradio-lfi.yaml'
    - 'http/vulnerabilities/gradio/gradio-ssrf.yaml'
    - 'http/vulnerabilities/other/fastadmin-lfi.yaml'
    - 'network/detection/mikrotik-ssh-detect.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    if: github.repository == 'projectdiscovery/nuclei-templates'
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
